// SPDX-License-Identifier: GPL-3.0-only
// Devvit trigger + scheduler endpoints.

import { Hono } from 'hono';
import { context } from '@devvit/web/server';
import { processInboundModmail, runScan } from '../core/automailScan';
import { invalidateRulePolicyCaches, listSubscribers } from '../core/automailStore';

export const triggers = new Hono();

type ModActionTriggerEvent = {
  action?: string;
  type?: string;
  description?: string;
  details?: string;
};

const RULE_ACTION = /\b(?:create|edit|delete|reorder)rules?\b/i;

export function isRuleChangeAction(event: ModActionTriggerEvent): boolean {
  const signal = [event.action, event.type, event.description, event.details]
    .filter((v): v is string => typeof v === 'string' && v.trim().length > 0)
    .join(' ')
    .toLowerCase();
  return RULE_ACTION.test(signal);
}

triggers.post('/on-modmail', async (c) => {
  const sub = context.subredditName;
  if (!sub) return c.json({ ok: false, reason: 'no-sub' }, 200);

  let event: {
    conversationId?: string;
    messageAuthor?: { isAdmin?: boolean };
    isAutoGenerated?: boolean;
  } = {};
  try {
    event = await c.req.json();
  } catch { /* tolerate */ }

  const conversationId = event.conversationId;
  if (!conversationId) return c.json({ ok: false, reason: 'no-convo-id' }, 200);

  const r = await processInboundModmail({
    sub,
    conversationId,
    isAutoGenerated: Boolean(event.isAutoGenerated),
  });
  return c.json({ ok: r.acted, reason: r.reason }, 200);
});

triggers.post('/on-mod-action', async (c) => {
  const sub = context.subredditName;
  if (!sub) return c.json({ ok: false, reason: 'no-sub' }, 200);

  let event: ModActionTriggerEvent = {};
  try {
    event = await c.req.json() as ModActionTriggerEvent;
  } catch { /* tolerate */ }

  if (!isRuleChangeAction(event)) {
    return c.json({ ok: true, invalidated: false, reason: 'not-rule-change' }, 200);
  }

  const invalidated = await invalidateRulePolicyCaches(sub, { includeTonePrompt: true });
  return c.json({ ok: true, invalidated: true, caches: invalidated }, 200);
});

triggers.post('/automail-scan-tick', async (c) => {
  const subs = await listSubscribers();
  let totalScanned = 0;
  let totalReplied = 0;
  let totalErrors = 0;
  for (const sub of subs) {
    try {
      const r = await runScan(sub);
      totalScanned += r.scanned;
      totalReplied += r.replied;
      totalErrors += r.errors;
    } catch (err) {
      totalErrors++;
      console.warn('[amu/scan-tick] sub', sub, 'failed:', err);
    }
  }
  return c.json({ ok: true, subs: subs.length, scanned: totalScanned, replied: totalReplied, errors: totalErrors });
});

export const __testables = { isRuleChangeAction };
